  version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "daily"
      open-pull-requests-limit: 10
      groups:
        vue:
          patterns:
            - 'vue*'
            - '@vue*'
          update-types:
            - minor
            - patch
        typescript:
          patterns:
            - 'typescript*'
            - '@typescript*'
          update-types:
            - minor
            - patch
        eslint:
          patterns:
            - 'eslint*'
            - '@eslint*'
          update-types:
            - minor
            - patch
