  version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "daily"
      open-pull-requests-limit: 10
      groups:
        vue:
          patterns:
            - 'vue*'
            - '@vue*'
          update-types:
            - major
            - minor
            - patch
        typescript:
          patterns:
            - 'typescript*'
            - '@typescript*'
          update-types:
            - major
            - minor
            - patch
        eslint:
          patterns:
            - 'eslint*'
            - '@eslint*'
            - '@typescript-eslint*'
          update-types:
            - major
            - minor
            - patch
        stryker-mutator:
          patterns:
            - 'stryker-mutator*'
            - '@stryker-mutator*'
          update-types:
            - major
            - minor
            - patch
        jest:
          patterns:
            - 'jest*'
            - 'ts-jest*'
            - 'babel-jest*'
            - '*-jest'
            - '@types/jest'
          update-types:
            - major
            - minor
            - patch
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
