# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Mount Dev Dependency Cache
      uses: actions/cache@v3
      with:
        key: cache-dev-dependencies-${{ github.run_id }}
        path: |
          .reports
          node_modules
    - run: make install

  # ------------------------------------------------------------------------------------------------------------------------

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs: install

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            .reports
            node_modules
      - run: make lint

  # ------------------------------------------------------------------------------------------------------------------------

  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs: install

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            .reports
            node_modules
      - run: make test-unit

  stryker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs:
      - install
      - unit

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            .reports
            node_modules
      - run: make test-stryker

  publish-test-results:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs:
      - install
      - unit
      - stryker
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            .reports
            node_modules
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./reports/jest/coverage-final.json

  # ------------------------------------------------------------------------------------------------------------------------

  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs:
      - install
      - lint
      - unit
      - stryker

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Mount Dev Dependency Cache
      uses: actions/cache@v3
      with:
        key: cache-dev-dependencies-${{ github.run_id }}
        path: |
          .reports
          node_modules

    - run: npm run build --if-present
    - name: publish to gh
      uses: ./.github/actions/vue-publish
      with:
        username: 'm3gg3r'
        reponame: 'pt'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      if: github.ref == 'refs/heads/main'
